### ISSUE TITLE
Joomla!4 & Bootstrap

### ISSUE THREAD

**Issue by ciar4n** [joomla-projects/user-experience#1]
Hi folks

I am not sure if this where one starts some discussion on future UI in Joomla but gonna take a leap of faith and go ahead (feel free to correct me if I should be starting this discussion elsewhere). Is the intention to create a new admin template for Joomla! 4 or simply improve on the current Isis template? With the hope that we will be moving on from Bootstrap 2.x, can we make a presumption on what CSS library will be used and begin work from there or do we wait until it is set in stone? A bit of foresight on this I imagine would help get things moving along a bit quicker, in particular with this group.

Ciarán

**Comment by ghost** [comment]
Thanks for your comment. This is the right place, and there have already been discussions, but we literally just opened this github project last week and haven't put anything up yet. 

My understanding is J4 will use the current stable version of bootstrap at the time of release, no one knows for sure when J4 will be ready, or when BS4 will become stable, so we can't say for sure if it's BS3 or 4. I can say it will be easier to update the underlying framework, because that's the real issue we have now.

We are working on a new front end template for J3.7, and have also done some research on an admin template for 3.7. The backend interface is not currently flexible enough to build the backend I want for the new front end template, so we'll be making some improvements back there sooner than J4. Just FYI :)

**Comment by ciar4n** [comment]
Ah excellent and thank you for the update. Sounds like everything is already moving in a very positive and definite direction. I will watch this space and look forward to testing and hopefully contributing to the fruits of your labor when available.

Ciarán
